# Generated by Django 4.1.3 on 2022-12-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='opening_article',
            new_name='article',
        ),
    ]
