# Generated by Django 4.1.3 on 2022-12-13 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_who_liked_comment',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
