# Generated by Django 4.1.3 on 2022-12-10 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid Email')], verbose_name='email address'),
        ),
    ]
