# Generated by Django 4.1.3 on 2022-12-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='article_images',
            field=models.ManyToManyField(blank=True, default=None, to='website.articleimage'),
        ),
    ]
