# Generated by Django 4.1.3 on 2022-12-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_subtopic_article_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=50)),
                ('resource_summary', models.CharField(max_length=150)),
                ('resource_url', models.URLField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='article_images',
            field=models.ManyToManyField(to='website.articleimage'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='article_resources',
            field=models.ManyToManyField(to='website.resource'),
        ),
    ]
